mod account;
mod activity;
mod agents;
mod ai;
mod ai_generate;
mod app_plugins;
mod cli_install;
mod cloud_sync;
mod community;
mod credentials;
mod flags;
mod global_mcp;
mod groups;
mod hooks;
mod instructions;
mod library;
mod mcp_servers;
mod memory;
mod misc;
mod oauth;
mod profile;
mod project_files;
mod projects;
mod recommendations;
mod remote_sources;
mod rules;
mod settings;
mod skill_store;
mod skills;
mod subagents;
mod task_log;
mod templates;
mod tokens;
mod tools;
mod user_commands;
mod whats_new;

pub use crate::plugins::build::commands::*;
pub use crate::plugins::dev_servers::commands::*;
pub use crate::plugins::maildev::commands::*;
pub use account::*;
pub use activity::*;
pub use agents::*;
pub use ai::*;
pub use ai_generate::*;
pub use app_plugins::*;
pub use cli_install::*;
pub use cloud_sync::*;
pub use community::*;
pub use credentials::*;
pub use flags::*;
pub use global_mcp::*;
pub use groups::*;
pub use hooks::*;
pub use instructions::*;
pub use library::*;
pub use mcp_servers::*;
pub use memory::*;
pub use misc::*;
pub use oauth::*;
pub use profile::*;
pub use project_files::*;
pub use projects::*;
pub use recommendations::*;
pub use remote_sources::*;
pub use rules::*;
pub use settings::*;
pub use skill_store::*;
pub use skills::*;
pub use subagents::*;
pub use task_log::*;
pub use templates::*;
pub use tokens::*;
pub use tools::*;
pub use user_commands::*;
pub use whats_new::*;

// ── Plugin dispatch ───────────────────────────────────────────────────────────
// All plugin commands flow through the single `invoke_tool_command` dispatcher
// defined in tools.rs.  No individual plugin command name appears here or in
// lib.rs.  The dispatch table in tools.rs maps tool names to plugin dispatch
// functions; plugin folders are entirely self-contained.
