// Keychain service name — debug builds use a separate entry so "Always Allow"
// only needs to be clicked once per build type, and dev/release entries never
// collide.
#[cfg(debug_assertions)]
pub const KEYCHAIN_SERVICE: &str = "automatic_desktop_dev";
#[cfg(not(debug_assertions))]
pub const KEYCHAIN_SERVICE: &str = "automatic_desktop";

pub mod agents;
pub mod ai;
pub mod ai_generate;
mod app_plugins;
mod asset_security;
mod author;
mod bundled_skills;
pub mod cli_install;
pub mod cloud_sync;
pub mod cloud_sync_diff;
pub mod cloud_sync_reconcile;
pub mod cloud_sync_state;
mod commands;
mod credentials;
mod editors;
mod env_crypto;
mod flags;
pub mod gitignore;
mod groups;
mod hooks;
mod integrations;
mod discover;
mod discover_data;
mod instructions;
mod mcp_servers;
mod paths;
mod plugins;
pub mod remote_sources;
mod profile;
mod project_files;
mod projects;
mod rules;
mod rules_injection;
mod settings;
mod skill_store;
mod skills;
mod subagents;
pub mod task_log;
mod templates;
pub mod tools;
mod types;
mod recently_added;
mod whats_new;

pub use app_plugins::*;
pub use asset_security::*;
pub use author::*;
pub use bundled_skills::*;
pub use cloud_sync::*;
pub use commands::*;
pub use credentials::*;
pub use editors::*;
pub use flags::*;
pub use groups::*;
pub use hooks::*;
pub use integrations::*;
pub use discover::*;
pub use discover_data::init_discover_files;
pub use instructions::*;
pub use mcp_servers::*;
pub use paths::*;
pub use plugins::*;
pub use profile::*;
pub use project_files::*;
pub use projects::*;
pub use rules::*;
pub use rules_injection::*;
pub use settings::*;
pub use skill_store::*;
pub use skills::*;
pub use subagents::*;
pub use templates::*;
pub use tools::*;
pub use types::*;
pub use recently_added::*;
pub use whats_new::*;
